version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/edata/minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345677
    command: server /data --console-address ":9001"